### PR TITLE
Add support for json lines

### PR DESCRIPTION
**Pull request by cactusdualcore**
In accordance with SemVer, I bumped the minor version. Not too sure whether this I wanted though.

### CODE REVIEW

**Comment by cactusdualcore** [comment]
I was thinking about adding hjson support as well. If that is desired, I could implement it too. If possibly, I would include it in this PR before merging so as to only bump the version to 0.12?

**Comment by NiklasEi** [comment]
I don't see the benefit of json lines over a "normal" json file containing an array. Do you have a use case that does not work with normal json?

**Comment by cactusdualcore** [comment]
> I don't see the benefit of json lines over a "normal" json file containing an array. Do you have a use case that does not work with normal json?

It's two parts preference, one part convenience. There _are_ technical reasons why one would prefer jsonlines over standard json, most importantly improved streamability, i.e. it's trivial to incrementally read and write the jsonlines format.

Ideally, I would have implemented something like

```rust
asset_server.load("all_the_assets.jsonl#1"); // loads the asset in the jsonlines file
``` 

This would allow short circuiting the asset loader for large files. I don't know enough about Bevy asset loaders to implement this well.

Besides streaming I can't think of any technical advantages of jsonlines though. Either way, it's effortless to convert a json array to jsonlines and back. Just add/remove brackets and commas.

**Comment by NiklasEi** [comment]
I would prefer not to add this format since I see little benefit over "normal" json, sorry. Thank you for the PR though!

**Pull request closed without merging**
